### ISSUE TITLE
Custom framerate not applying

### ISSUE THREAD

**Issue by Repflez** [Repflez/TaikoModStuff#1]
Known bug. I think I found the issue.

Thanks Namco.

**Comment by Repflez** [comment]
Attempt 1 is on [Release 1.1.1](https://github.com/Repflez/TaikoModStuff/releases/tag/1.1.1)

**Comment by Repflez** [comment]
Attempt 1 is on [Release 1.1.1](https://github.com/Repflez/TaikoModStuff/releases/tag/1.1.1)

**Comment by 165732** [comment]
still not working with 1.1.1

**Comment by Repflez** [comment]
> still not working with 1.1.1

I am aware, I did found what is the actual cause, from what I see.

**Comment by Repflez** [comment]
Fixed in [1.2.0](https://github.com/Repflez/TaikoModStuff/releases/tag/1.2.0)
