### ISSUE TITLE
TaikoModStuff doesn't work on 1.8+ due to a Unity update

### ISSUE THREAD

**Issue by Elasder123** [Repflez/TaikoModStuff#10]
Tried the mod but it won't work at all in the new version of the game which is 1.8.0.0

**Comment by Repflez** [comment]
BepinEx is not compatible with the version of Unity 1.8.0.0 uses. This breaks every plugin, including TaikoModStuff and TakoTako. We're waiting for an update to BepinEx so it can support the latest version.

**Comment by Elasder123** [comment]
oooh alright then. I hope there will be a new update soon then
