### ISSUE TITLE
BepInEx does not discover plugin

### ISSUE THREAD

**Issue by yuri-becker** [Repflez/TaikoModStuff#11]
I've followed the instructions but the plugin does not load and the BepInEx startup log says "0 plugins to load" (and "0 patcher plugins loaded")

**Comment by shacha086** [comment]
+1, using bepinex6.0

**Comment by calbeeb** [comment]
same issue, downloaded another plugin and can confirm it works. seems to be that bepinex is looking for a folder named com.xxx.xxx containing the files we download here, with the dll following the same naming scheme.
![image](https://user-images.githubusercontent.com/122324100/211427780-877db520-9c08-49b3-ab72-5f664dbaf65e.png)
![image](https://user-images.githubusercontent.com/122324100/211427805-6d8741c3-986b-4be0-945e-ce2fe450cc82.png)

**Comment by Repflez** [comment]
I have tested this and seems to work as normal without the need to create a folder for the plugin

**Comment by Repflez** [comment]
Does this seem to be fixed with the latest build?

**Comment by calbeeb** [comment]
Yep, 1.4 wasn't available for me a couple days ago but it's fixed the issue. Thought that just updating to a new BepInEx version was the fix for 1.3.1

**Comment by Repflez** [comment]
All right. I guess updating the meta library for the plugin did the job, but it works now, so I'll close this
