### ISSUE TITLE
1.3.1.0 update broke TaikoModStuff

### ISSUE THREAD

**Issue by melomori** [Repflez/TaikoModStuff#4]
Title is self explanatory, 1.3.1.0 update that released around 10PM CST on February 20th, 2022 broke TaikoModStuff.

Recopying files and all that doesn’t make the config come up anymore, yadda yadda..thanks Namco!

**Comment by Repflez** [comment]
Found up just now, will push an update later tomorrow

**Comment by Repflez** [comment]
Should be fixed in the latest release
