### ISSUE TITLE
Current plugin won't work with IL2CPP...

### ISSUE THREAD

**Issue by AspirineHD** [Repflez/TaikoModStuff#5]
The latest update broke the plugin. It changed from Mono runtime to IL2CPP runtime. 
Even I managed to make the BepInEx work again (using BepInEx Bleeding Edge) but the current plugin won't work with IL2CPP.

Hope you hear this.
Thank you in advance

**Comment by AspirineHD** [comment]
I FIXED IT!!!
I managed to create the plugin on IL2CPP based on your awesome code 👍 
![image](https://user-images.githubusercontent.com/47499678/155025923-cc9db615-4b56-4e91-b1a6-ec9303ccadba.png)

**Comment by Repflez** [comment]
Ah, I was unaware of the update until now! I'll push an update tomorrow for it, then

**Comment by Repflez** [comment]
Updated to 1.3.0
